name: Sector Cycle Update

on:
  schedule:
    # 平日 18:00 (JST)
    - cron: '0 9 * * 1-5'
  workflow_dispatch:

jobs:
  update-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write # GitHub Pagesへのデプロイに必要
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Script & Generate HTML
        env:
          WP_SECRETS_JSON: ${{ secrets.WP_SECRETS_JSON }}
        run: python src/main.py

      # 生成された public フォルダを GitHub Pages (gh-pagesブランチ) にデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # gh-pagesブランチにindex.htmlだけを配置します
